name: Build Release
on:
  - push
  - pull_request
permissions: {}
jobs:
  check-latest-versions:
    permissions:
      contents: read
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check latest versions
        run: ./check-latest-versions.sh
  create-release-for-tag:
    permissions:
      contents: write
    runs-on: 'ubuntu-24.04'
    needs: check-latest-versions
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          omitBody: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    needs: create-release-for-tag
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-24.04'
        platform:
          - 'linux-x64'
          - 'linux-armv6'
          - 'linuxmusl-x64'
          - 'linux-ppc64le'
          - 'linux-s390x'
          - 'wasm32'
          - 'win32-ia32'
          - 'win32-x64'
          - 'win32-arm64v8'
        include:
          - os: macos-13
            platform: 'darwin-x64'
          - os: macos-13
            platform: 'darwin-arm64v8'
          - os: 'ubuntu-24.04-arm'
            platform: 'linux-arm64v8'
          - os: 'ubuntu-24.04-arm'
            platform: 'linuxmusl-arm64v8'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pip3 install meson==1.7.2 ninja packaging
          brew install automake nasm
      - name: Build ${{ matrix.platform }}
        id: build-release
        run: ./build.sh ${{ matrix.platform }}
      - name: Upload Release Asset (.tar.gz)
        id: upload-release-asset-gz
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: libvips-*-${{ matrix.platform }}.tar.gz
          artifactContentType: application/gzip
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
